//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RVVPM.rc
//
#define IDRESET                         3
#define IDD_ABOUTBOX                    100
#define IDD_RVVPM_FORM                  101
#define IDR_MAINFRAME                   128
#define IDR_RVVPMTYPE                   129
#define IDD_PORTDLG                     130
#define IDD_PROPPAGE_COLUMNS            131
#define IDD_PROPPAGE_SOURCE             132
#define IDD_DIALOG1                     133
#define IDD_TRIGGER                     133
#define IDR_PORTFOLIO                   137
#define IDR_TRIGGER                     138
#define IDD_PROPPAGE_SYMTRIGGER         139
#define IDD_PROPAGE_OTRTRIGGER          140
#define IDR_URLS                        141
#define IDD_URLS                        142
#define IDR_PROFOLIO                    144
#define IDR_URL                         145
#define IDR_PROFOLIO1                   146
#define IDI_RIGHT1                      152
#define IDI_LEFT1                       153
#define IDI_DOWN1                       154
#define IDI_UP1                         155
#define IDI_PORTF                       156
#define IDI_RESET                       161
#define IDI_DUMMY                       164
#define IDD_LOGIN                       165
#define IDI_REMOVE                      172
#define IDI_ADD                         173
#define IDC_EDIT2                       1001
#define IDC_COMBO1                      1002
#define IDC_LIST1                       1003
#define IDC_EDIT_HIGHPR                 1003
#define IDC_LIST2                       1004
#define IDC_ADD                         1005
#define IDC_RESET                       1005
#define IDC_REMOVE                      1006
#define IDC_PASSWD                      1006
#define IDC_UP                          1007
#define IDC_USERID                      1007
#define IDC_EDIT3                       1007
#define IDC_EDIT_LOWPR                  1007
#define IDC_DOWN                        1008
#define IDC_AUTO                        1008
#define IDC_EDIT4                       1009
#define IDC_EDIT_HIGHPTS                1009
#define IDC_SAVE                        1009
#define IDC_AUTO2                       1009
#define IDC_QUOTE                       1010
#define IDC_EDIT5                       1010
#define IDC_EDIT_LOWPTS                 1010
#define IDC_NEWS                        1011
#define IDC_EDIT6                       1011
#define IDC_EDIT_HIGHMV_TD              1011
#define IDC_QUOTE2                      1011
#define IDC_EDIT7                       1012
#define IDC_EDIT_LOWPC                  1012
#define IDC_CHECK1                      1012
#define IDC_AUTO3                       1012
#define IDC_EDIT9                       1013
#define IDC_EDIT_HIGHMVPTS              1013
#define IDC_EDIT10                      1014
#define IDC_EDIT_HIGHPC                 1014
#define IDC_EDIT_HIGHMVPRC              1015
#define IDC_EDIT8                       1016
#define IDC_EDIT_LOWMV_TD               1016
#define IDC_SYSLINK3                    1016
#define IDC_EDIT11                      1017
#define IDC_EDIT_LOW_MV_PTS             1017
#define IDC_MFCLINK2                    1017
#define IDC_EDIT_BOUGHT                 1018
#define IDC_EDIT_HIGHMV_TDPRC           1018
#define IDC_CHKDOW                      1018
#define IDC_EDIT_PAID                   1019
#define IDC_EDIT_LOW_MV_PRC             1019
#define IDC_CHKDOW2                     1019
#define IDC_EDIT_NEWPD                  1020
#define IDC_EDIT_LOWMV_TDPRC            1020
#define IDC_EDIT1                       1020
#define IDC_AUTO4                       1021
#define IDC_CHKDOW3                     1021
#define IDC_EDIT_NEWPD2                 1022
#define IDC_COMBO2                      1100
#define ID_PM_NEW                       32771
#define ID_PM_OPEN                      32773
#define ID_PM_EDIT                      32775
#define ID_PM_DELETE                    32776
#define ID_PM_SEETINGS                  32777
#define ID_PM_NEWS                      32778
#define ID_PM_ONEDAY                    32779
#define ID_PM_FIVEDAY                   32780
#define ID_PM_THREEMONTH                32781
#define ID_PM_ISLAND                    32782
#define ID_PM_TRIGGER                   32783
#define ID_PM_PRINT                     32784
#define ID_QM_NEW                       32785
#define ID_QM_OPEN                      32786
#define ID_QM_DELETE                    32787
#define ID_QM_SAVE                      32789
#define ID_QM_RESET                     32790
#define ID_MENUITEM32791                32791
#define ID_QM_URLS                      32792
#define ID_QM_BAK                       32796
#define ID_QM_FWD                       32797
#define ID_BUTTON32798                  32798
#define ID_QM_REFRESH                   32799
#define ID_QM_RUN                       32800
#define ID_QM_NEWPF                     32801
#define ID_QM_SAVEPF                    32802
#define ID_QM_DELETEPF                  32803
#define ID_QM_NEWBM                     32804
#define ID_QM_SAVEBM                    32805
#define ID_QM_DELETEBM                  32806
#define ID_PM_QREFRESH                  32807
#define ID_PM_NREFRESH                  32808
#define ID_DOW_PANE                     33000
#define ID_NASDAQ_PANE                  33001
#define ID_TIME_PANE                    33002
#define ID_BUSY_PANE                    33003
#define PM_FIRSTCOLUMN                  61500
#define PM_EXCHANGE                     61501
#define PM_SYMBOL                       61502
#define PM_ALARAM                       61503
#define PM_LASTTRADE                    61504
#define PM_CHANGE                       61505
#define PM_CHANGE2                      61506
#define PM_CHANGE3                      61507
#define PM_CHANGE4                      61508
#define PM_CHANGE5                      61509
#define PM_OPEN                         61510
#define PM_VOLUME                       61511
#define PM_ASK                          61512
#define PM_BID                          61513
#define PM_CLOSEDAY1                    61514
#define PM_CLOSEDAY2                    61515
#define PM_CLOSEDAY3                    61516
#define PM_CLOSEDAY4                    61517
#define PM_CLOSEDAY5                    61518
#define PM_DAYRANGE                     61519
#define PM_52WKRANGE                    61520
#define PM_BOUGHT                       61521
#define PM_PAID                         61522
#define PM_GAIN                         61523
#define PM_HGHALRM                      61524
#define PM_LOWALRM                      61525
#define PM_ACTVALUE                     61526
#define PM_LASTCOLUMN                   61527

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
