using System;
using UITesting.Automated.UIADriver;

namespace autogenerated
{
    class UIAAutomationElement
    {
        static private UIAElement uiaelement;

        static UIAAutomationElement()
        {
            uiaelement = new UIAElement();
        }

        static public UIAElement UIADriver
        {
            get
            {
                return uiaelement;
            }
        }
    }

    class sample
    {

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Clear_clearButton_1300_500
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Clear_clearButton_1300_500\",        \"AEType\":\"button\",        \"AEText\":\"Clear\",        \"AEAutomationId\":\"clearButton\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 6 1 \",        \"CenterPoint\":\"128,287\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Eight_num8Button_1300_554
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Eight_num8Button_1300_554\",        \"AEType\":\"button\",        \"AEText\":\"Eight\",        \"AEAutomationId\":\"num8Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 8 \",        \"CenterPoint\":\"128,341\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Seven_num7Button_1222_554
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Seven_num7Button_1222_554\",        \"AEType\":\"button\",        \"AEText\":\"Seven\",        \"AEAutomationId\":\"num7Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 7 \",        \"CenterPoint\":\"50,341\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Four_num4Button_1222_608
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Four_num4Button_1222_608\",        \"AEType\":\"button\",        \"AEText\":\"Four\",        \"AEAutomationId\":\"num4Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 4 \",        \"CenterPoint\":\"50,395\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Multiply_by_multiplyButton_1457_554
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Multiply_by_multiplyButton_1457_554\",        \"AEType\":\"button\",        \"AEText\":\"Multiply by\",        \"AEAutomationId\":\"multiplyButton\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 5 1 \",        \"CenterPoint\":\"285,341\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_One_num1Button_1222_662
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_One_num1Button_1222_662\",        \"AEType\":\"button\",        \"AEText\":\"One\",        \"AEAutomationId\":\"num1Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 1 \",        \"CenterPoint\":\"50,449\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Six_num6Button_1379_608
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Six_num6Button_1379_608\",        \"AEType\":\"button\",        \"AEText\":\"Six\",        \"AEAutomationId\":\"num6Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 6 \",        \"CenterPoint\":\"207,395\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Nine_num9Button_1379_554
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Nine_num9Button_1379_554\",        \"AEType\":\"button\",        \"AEText\":\"Nine\",        \"AEAutomationId\":\"num9Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 9 \",        \"CenterPoint\":\"207,341\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Five_num5Button_1300_608
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Five_num5Button_1300_608\",        \"AEType\":\"button\",        \"AEText\":\"Five\",        \"AEAutomationId\":\"num5Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 5 \",        \"CenterPoint\":\"128,395\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Zero_num0Button_1300_716
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Zero_num0Button_1300_716\",        \"AEType\":\"button\",        \"AEText\":\"Zero\",        \"AEAutomationId\":\"num0Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 7 0 \",        \"CenterPoint\":\"128,503\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Equals_equalButton_1457_716
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Equals_equalButton_1457_716\",        \"AEType\":\"button\",        \"AEText\":\"Equals\",        \"AEAutomationId\":\"equalButton\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 3 5 4 \",        \"CenterPoint\":\"285,503\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_1210_239\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"3,270\"    }}";
            }
        }
    }

    //  ***************Playback Code********************
    class Player
    {

        static jsonparser jspobj = new jsonparser();
        static sample objsample = new sample();

        static object ParseObj( object injson,  object field)
        {
            return jspobj.ParseObj(injson, field);
        }

        public static void Main()
        {
            string brs = null;
System.Diagnostics.Process.Start("calc.exe");
System.Threading.Thread.Sleep(2000);

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Clear_clearButton_1300_500);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Eight_num8Button_1300_554);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Seven_num7Button_1222_554);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Eight_num8Button_1300_554);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Four_num4Button_1222_608);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Multiply_by_multiplyButton_1457_554);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_One_num1Button_1222_662);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Six_num6Button_1379_608);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Multiply_by_multiplyButton_1457_554);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Nine_num9Button_1379_554);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Five_num5Button_1300_608);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Zero_num0Button_1300_716);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Equals_equalButton_1457_716);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();
        }

    }

}

