using System;
using UITesting.Automated.UIADriver;

namespace autogenerated
{
    class UIAAutomationElement
    {
        static private UIAElement uiaelement;

        static UIAAutomationElement()
        {
            uiaelement = new UIAElement();
        }

        static public UIAElement UIADriver
        {
            get
            {
                return uiaelement;
            }
        }
    }

    class sample
    {

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Clear_clearButton_3353_744
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Clear_clearButton_3353_744\",        \"AEType\":\"button\",        \"AEText\":\"Clear\",        \"AEAutomationId\":\"clearButton\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 4 2 \",        \"CenterPoint\":\"258,272\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Eight_num8Button_3254_872
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Eight_num8Button_3254_872\",        \"AEType\":\"button\",        \"AEText\":\"Eight\",        \"AEAutomationId\":\"num8Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 8 \",        \"CenterPoint\":\"159,400\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Seven_num7Button_3155_872
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Seven_num7Button_3155_872\",        \"AEType\":\"button\",        \"AEText\":\"Seven\",        \"AEAutomationId\":\"num7Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 7 \",        \"CenterPoint\":\"60,400\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Four_num4Button_3155_936
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Four_num4Button_3155_936\",        \"AEType\":\"button\",        \"AEText\":\"Four\",        \"AEAutomationId\":\"num4Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 4 \",        \"CenterPoint\":\"60,464\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Multiply_by_multiplyButton_3452_872
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Multiply_by_multiplyButton_3452_872\",        \"AEType\":\"button\",        \"AEText\":\"Multiply by\",        \"AEAutomationId\":\"multiplyButton\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 6 1 \",        \"CenterPoint\":\"357,400\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_One_num1Button_3155_1000
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_One_num1Button_3155_1000\",        \"AEType\":\"button\",        \"AEText\":\"One\",        \"AEAutomationId\":\"num1Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 1 \",        \"CenterPoint\":\"60,528\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Six_num6Button_3353_936
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Six_num6Button_3353_936\",        \"AEType\":\"button\",        \"AEText\":\"Six\",        \"AEAutomationId\":\"num6Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 6 \",        \"CenterPoint\":\"258,464\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Five_num5Button_3254_936
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Five_num5Button_3254_936\",        \"AEType\":\"button\",        \"AEText\":\"Five\",        \"AEAutomationId\":\"num5Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 5 \",        \"CenterPoint\":\"159,464\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Zero_num0Button_3254_1064
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Zero_num0Button_3254_1064\",        \"AEType\":\"button\",        \"AEText\":\"Zero\",        \"AEAutomationId\":\"num0Button\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 7 0 \",        \"CenterPoint\":\"159,592\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }

        //supported patterns:MSAAAccessible,Generic,Invoke,Navigation,ScrollItem
        public string button_Equals_equalButton_3452_1064
        {
            get
            {
                return "{    \"ci\":    {        \"UserName\":\"button_Equals_equalButton_3452_1064\",        \"AEType\":\"button\",        \"AEText\":\"Equals\",        \"AEAutomationId\":\"equalButton\",        \"Patterns\":\"Invoke,ScrollItem\",        \"Path\":\"1 2 1 6 4 \",        \"CenterPoint\":\"357,592\"    },    \"ciroot\":    {        \"UserName\":\"window_Calculator_3143_503\",        \"AEType\":\"window\",        \"AEText\":\"Calculator\",        \"AEAutomationId\":\"\",        \"Patterns\":\"Window,Transform\",        \"Path\":\"\",        \"CenterPoint\":\"209,634\"    }}";
            }
        }
    }

    //  ***************Playback Code********************
    class Player
    {

        static jsonparser jspobj = new jsonparser();
        static sample objsample = new sample();

        static object ParseObj( object injson,  object field)
        {
            return jspobj.ParseObj(injson, field);
        }

        public static void Main()
        {
            string brs = null;

	System.Diagnostics.Process.Start("calc.exe");
	System.Threading.Thread.Sleep(2000);

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Clear_clearButton_3353_744);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Eight_num8Button_3254_872);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Seven_num7Button_3155_872);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Eight_num8Button_3254_872);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Four_num4Button_3155_936);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Multiply_by_multiplyButton_3452_872);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_One_num1Button_3155_1000);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Six_num6Button_3353_936);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Multiply_by_multiplyButton_3452_872);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_One_num1Button_3155_1000);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Five_num5Button_3254_936);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Zero_num0Button_3254_1064);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();

            UIAAutomationElement.UIADriver.SetAutomationElement (objsample.button_Equals_equalButton_3452_1064);
            UIAAutomationElement.UIADriver.ProviderInvoke.Click();
        }

    }

}

