using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using autogenerated;
using autogenerated2;

namespace calctest
{
    class Program
    {
        static bool bwcf = false;
        static string ipad = "127.0.0.1";

        static string lbaddcall(int num1, int num2)
        {
            COM_LB_SillyCalc_WSC_1 lbclt = new COM_LB_SillyCalc_WSC_1(ipad);
            return lbclt.add( num1, num2).ToString();
        }



        static string wcfaddcall(int num1, int num2)
        {
            ServiceReference1.SillyCalc_WSC_1Client wcfclt = new ServiceReference1.SillyCalc_WSC_1Client("NetNamedPipeBinding_ISillyCalc_WSC_1");
            return wcfclt.add(num1, num2).ToString();
        }

        static void Main(string[] args)
        {
            if (args.Length != 1 && args.Length != 2)
            {
                Console.WriteLine("syntax:calctest {wcf}|{lb serverip}");
                return;
            }


            if (!(bwcf = (args[0] == "wcf")))
                ipad = args[1];

            int num1 = 25;
            int num2 = 10;
            string ret = "";

            if (!bwcf)
            {
                ret = lbaddcall(num1, num2);
                Console.WriteLine("Late Binding call: add({0},{1}) = {2}", num1, num2, ret);
            }
            else
            {
                autogenerated2.CSComAdmin.StartStop_wcfserver_WSC_1("", true);
                ret = wcfaddcall(num1,num2);
                Console.WriteLine("wcf call: add({0},{1}) = {2}", num1, num2, ret);
            }
            Console.ReadKey();
        }
    }
}
